### ISSUE TITLE
Build branches

### ISSUE THREAD

**Issue by tsloughter** [tsloughter/erlup#20]
erlup should be able to build branches of a repo not just tags.

**Comment by lrascao** [comment]
maybe a `repo` default branch sub-option?

**Comment by tsloughter** [comment]
hm? Not sure what you mean. I just mean `erlup build <tag>` should also allow a branch instead of tag. Right now it fails because it can't check it out.

**Comment by lrascao** [comment]
yeah, that is simpler. Was thinking of appending a default branch to the repo config so you can just say `build` instead of `build <branch>`

**Comment by tsloughter** [comment]
ah
