### ISSUE TITLE
Fails in ./configure

### ISSUE THREAD

**Issue by tsloughter** [tsloughter/erlup#21]
I have no idea what is going on. I get:

```
checking whether the C compiler works... no
```

when running a build with `erlup`. But if I go to the directory it is running the commands in and run the configure manually it works fine.

Likely related to my environment (Fedora 33) somehow... but either way figured I'd open an issue in case anyone else has seen similar.

**Comment by rjcoelho** [comment]
Same issue on aarch64 when doing erlup build OTP-21.3.8.5

**Comment by tsloughter** [comment]
@rjcoelho what OS?

**Comment by rjcoelho** [comment]
Linux @tsloughter

**Comment by tsloughter** [comment]
@rjcoelho what distro?

**Comment by rjcoelho** [comment]
Amazon Linux 2

**Comment by tsloughter** [comment]
Interesting, so also a Red Hat based distro.

**Comment by rjcoelho** [comment]
running configure manually (with same args) works just like the original post described

**Comment by tsloughter** [comment]
Ugh. I disabled SELinux, rebooted and it still happens. I have no idea how this is happening or even where to start.

**Comment by tsloughter** [comment]
Oh, I figured it out. It is the `env_clear` that was added to Command.

@lrascao what was the reason for adding that clearing?

I'll make a PR to remove it, but maybe there is an alternative solution to consider?
