### ISSUE TITLE
Check if install dir is empty before erroring

### ISSUE THREAD

**Issue by tsloughter** [tsloughter/erlup#3]
Currently `erlup` simply fails if the dir like `OTP-23.1` exists and you attempt to do `erlup build OTP-23.1`, even if that dir is empty and was imply created so that it could be used for the `--prefix` when running the build but the compilation failed.

**Comment by lrascao** [comment]
probably #14 takes care of this one as well

**Comment by tsloughter** [comment]
Yup, closing.
