### ISSUE TITLE
Cleanup created directory if build fails

### ISSUE THREAD

**Issue by tsloughter** [tsloughter/erlup#4]
A directory is created before `configure` is called so it can be passed as the argument to `--prefix`. This directory should be removed if the build fails *and* it is empty -- to prevent against deleting deleting an old working install that was being overridden.

**Comment by lrascao** [comment]
#14 now aborts the pipeline if the build step fails, this ensures that a previously working install dir is not clobbered, so maybe we can close this one when PR is closed?

**Comment by tsloughter** [comment]
Looks good, yup.
